### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by hannraoi** [leehomyc/Photo-Realistic-Super-Resoluton#8]
Hi~when I run ur code : "t_folder=xxx model_folder=xxx th run_sr.lua", and I got an error like this:

hannraoi@hannraoi-B85M-DS3H:~/Photo-Realistic-Super-Resoluton-master$ t_folder=../MY_TRAIN_5/ model_folder=../MY_SRGAN_MODEL/ th run_sr.lua
{
  model_folder : "../MY_SRGAN_MODEL/"
  lr : 0.001
  batchSize : 32
  niter : 250
  loadSize : 96
  nThreads : 4
  name : "super_resolution"
  gpu : 1
  dataset : "folder"
  beta1 : 0.9
  ntrain : inf
  t_folder : "../MY_TRAIN_5/"
}
Starting donkey with id: 1 seed: 1
table: 0x7ff4a40bc400
Starting donkey with id: 3 seed: 3
table: 0x7ff49815e5c0
Starting donkey with id: 4 seed: 4
table: 0x7ff49006be60
Starting donkey with id: 2 seed: 2
table: 0x7ff49c0fa350
Loading train metadata from cache
Loading train metadata from cache
Loading train metadata from cache
Loading train metadata from cache
Dataset: folder	 Size: 	25	
cunn used	
THCudaCheck FAIL file=/home/hannraoi/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/home/hannraoi/torch/install/bin/lua: /home/hannraoi/torch/install/share/lua/5.2/optim/adam.lua:51: cuda runtime error (2) : out of memory at /home/hannraoi/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'new'
	/home/hannraoi/torch/install/share/lua/5.2/optim/adam.lua:51: in function 'adam'
	run_sr.lua:133: in main chunk
	[C]: in function 'dofile'
	...raoi/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

it says "out of memory". My machine has a GPU of GTX 660 with 2G ram, may I ask what kind of hardware equipment it takes to run ur code? How can I run ur code on my machine ? Thanks a lot~

**Comment by yangcheng001** [comment]
I also have this problem. 
My machine has a GPU of GTX 1050 Ti with 4G .when I try this commend, after two epoch,I also got the error "out of memory"

**Comment by CPFLAME** [comment]
You can reduce batchSize(32 -> 16)  and loadSize(96 -> 64 or 32).  And I have found that the memory usage will increase with the increase of iterations.

**Comment by yangcheng001** [comment]
thank you for your help

**Comment by hannraoi** [comment]
@CPFLAME sorry for replying so late, I have run this code on a higher equipment machine and it works well, but thank u for ur advice anyway.
